from . import patient
from . import medecin
from . import clinique
from . import consultation
from . import indications
from . import dataset
from . import allergies
from . import antecedents_medicaux
from . import medicaments_actuels
from . import categorie_age
from . import specialité
from . import demande_inscription
from . import molecule
from . import dynamed_prescription
from . import classe_medicale
from . import diagnostic
from . import nom_commercial
from . import interaction
from . import precaution
from . import dynamed_dashboard
